//
//  OperationTypes.h
//  Gastalon
//
//  Created by Yolanda Martínez on 27/03/15.
//  Copyright (c) 2015 Dragonfly Labs. All rights reserved.
//

#ifndef Gastalon_OperationTypes_h
#define Gastalon_OperationTypes_h

#define TRANSACTION_ADD_ACCOUNT 1
#define TRANSACTION_ADD_SHARED_ACCOUNT 2
#define TRANSACTION_ALARM_PAY 3
#define TRANSACTION_ALARM_PAY_GROUPAL 4
#define TRANSACTION_DID_YOU_GET_GROUP 5
#define TRANSACTION_DID_YOU_GET_THE_MONEY 6
#define TRANSACTION_FRIEND_ADDED_YOU_TO_ACCOUNT 7
#define TRANSACTION_FRIEND_GAIN_MONEY 8
#define TRANSACTION_FRIEND_SPENT_MONEY 9
#define TRANSACTION_YOU_ADDED_FRIEND_TO_ACCOUNT 10
#define TRANSACTION_YOU_ADDED_FRIENDS_TO_ACCOUNT 11
#define TRANSACTION_YOU_HAS_GAINED_IN_SHARED 12
#define TRANSACTION_YOU_HAS_GAINED_MONEY 13
#define TRANSACTION_YOU_HAS_SPENT 14
#define TRANSACTION_YOU_ADDED_A_CATEGORY 15

#endif
